FROM tibbw:6.3.1

MAINTAINER Daniel Hodrea <hodrea@mediamarktsaturn.com>

ADD docker-entrypoint.sh /opt/tibco/docker-entrypoint.sh
ADD tibco.bw.sample.binding.rest.Basic.application_1.0.0.ear /tibco.bw.sample.binding.rest.Basic.application_1.0.0.ear

#ENTRYPOINT ["/opt/tibco/docker-entrypoint.sh"]