apiVersion: v1
kind: Service
metadata:
  name: bw-sample-rest
  labels:
    app: samplerest
spec:
  type: LoadBalancer
  ports:
  - port: 8081
    targetPort: bw-sample-port
  selector:
    app: samplerest