apiVersion: v1
kind: Service
metadata:
  name: customems
  labels:
    app: customems
spec:
  type: LoadBalancer
  ports:
  - port: 7222
    targetPort: customems-port
  selector:
    app: customems
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: emsdata-pv-claim
  labels:
    app: customems
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: customems
  labels:
    app: customems
spec:
  replicas: 3
  selector:
    matchLabels:
      app: customems
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: customems
    spec:
      containers:
      - image: gcr.io/delta-heading-198209/customems:1.0.0
        name: customems
        ports:
        - containerPort: 7222
          name: customems-port
        volumeMounts:
        - name: emsdata
          mountPath: /opt/tibco/cfgmgmt/ems/data
      volumes:
      - name: emsdata
        persistentVolumeClaim:
          claimName: emsdata-pv-claim